//! Configuration and event types for the judge manager.

use bms_model::{LaneProperty, LnType, Note, PlayMode};

use crate::judge_algorithm::JudgeAlgorithm;
use crate::judge_property::JudgeProperty;

/// Configuration for initializing the JudgeManager.
pub struct JudgeConfig<'a> {
    /// All notes in the chart (sorted by time)
    pub notes: &'a [Note],
    /// Play mode
    pub play_mode: PlayMode,
    /// LN type from BMS header
    pub ln_type: LnType,
    /// Judge rank (#RANK value)
    pub judge_rank: i32,
    /// Judge window rate for [PG, GR, GD] (100 = normal)
    pub judge_window_rate: [i32; 3],
    /// Scratch judge window rate (100 = normal)
    pub scratch_judge_window_rate: [i32; 3],
    /// Note selection algorithm
    pub algorithm: JudgeAlgorithm,
    /// Whether autoplay is active
    pub autoplay: bool,
    /// Judge property set
    pub judge_property: &'a JudgeProperty,
    /// Lane property for key→lane mapping (optional, auto-created from play_mode if None)
    pub lane_property: Option<&'a LaneProperty>,
}

/// Events generated by JudgeManager during update.
#[derive(Debug, Clone, PartialEq)]
pub enum JudgeEvent {
    /// A note was judged.
    Judge {
        note_index: usize,
        lane: usize,
        judge: usize,
        duration: i64,
    },
    /// A key sound should play.
    KeySound { wav_id: u16 },
    /// Mine note damage.
    MineDamage { lane: usize, damage: i32 },
    /// HCN gauge update.
    HcnGauge { increase: bool },
}
