use crate::groove_gauge::GaugeModifier;

/// Gauge specification
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GaugeProperty {
    FiveKeys,
    SevenKeys,
    Pms,
    Keyboard,
    Lr2,
}

impl GaugeProperty {
    pub fn values() -> &'static [GaugeProperty] {
        &[
            GaugeProperty::FiveKeys,
            GaugeProperty::SevenKeys,
            GaugeProperty::Pms,
            GaugeProperty::Keyboard,
            GaugeProperty::Lr2,
        ]
    }

    pub fn name(&self) -> &str {
        match self {
            GaugeProperty::FiveKeys => "FIVEKEYS",
            GaugeProperty::SevenKeys => "SEVENKEYS",
            GaugeProperty::Pms => "PMS",
            GaugeProperty::Keyboard => "KEYBOARD",
            GaugeProperty::Lr2 => "LR2",
        }
    }

    pub fn get_values(&self) -> Vec<GaugeElementProperty> {
        match self {
            GaugeProperty::FiveKeys => vec![
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    100.0,
                    20.0,
                    50.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -1.5, -3.0, -0.5],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    100.0,
                    20.0,
                    75.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -1.5, -4.5, -1.0],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    100.0,
                    20.0,
                    75.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -3.0, -6.0, -2.0],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::LimitIncrement),
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.0, 0.0, 0.0, -5.0, -10.0, -5.0],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::ModifyDamage),
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.0, 0.0, 0.0, -10.0, -20.0, -10.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.0, 0.0, 0.0, -100.0, -100.0, -100.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.01, 0.01, 0.0, -0.5, -1.0, -0.5],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.01, 0.01, 0.0, -1.0, -2.0, -1.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.01, 0.01, 0.0, -2.5, -5.0, -2.5],
                    &[],
                ),
            ],
            GaugeProperty::SevenKeys => vec![
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    100.0,
                    20.0,
                    60.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -1.5, -3.0, -0.5],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    100.0,
                    20.0,
                    80.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -1.5, -4.5, -1.0],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    100.0,
                    20.0,
                    80.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -3.0, -6.0, -2.0],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::LimitIncrement),
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.15, 0.12, 0.03, -5.0, -10.0, -5.0],
                    &[
                        &[10.0, 0.4],
                        &[20.0, 0.5],
                        &[30.0, 0.6],
                        &[40.0, 0.7],
                        &[50.0, 0.8],
                    ],
                ),
                gep(
                    Some(GaugeModifier::LimitIncrement),
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.15, 0.06, 0.0, -8.0, -16.0, -8.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.15, 0.06, 0.0, -100.0, -100.0, -10.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.15, 0.12, 0.06, -1.5, -3.0, -1.5],
                    &[
                        &[5.0, 0.4],
                        &[10.0, 0.5],
                        &[15.0, 0.6],
                        &[20.0, 0.7],
                        &[25.0, 0.8],
                    ],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.15, 0.12, 0.03, -3.0, -6.0, -3.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.15, 0.06, 0.0, -5.0, -10.0, -5.0],
                    &[],
                ),
            ],
            GaugeProperty::Pms => vec![
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    120.0,
                    30.0,
                    65.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -1.0, -2.0, -2.0],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    120.0,
                    30.0,
                    85.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -1.0, -3.0, -3.0],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    120.0,
                    30.0,
                    85.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -2.0, -6.0, -6.0],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::LimitIncrement),
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.15, 0.12, 0.03, -5.0, -10.0, -10.0],
                    &[
                        &[10.0, 0.4],
                        &[20.0, 0.5],
                        &[30.0, 0.6],
                        &[40.0, 0.7],
                        &[50.0, 0.8],
                    ],
                ),
                gep(
                    Some(GaugeModifier::LimitIncrement),
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.15, 0.06, 0.0, -10.0, -15.0, -15.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.15, 0.06, 0.0, -100.0, -100.0, -100.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.15, 0.12, 0.06, -1.5, -3.0, -3.0],
                    &[
                        &[5.0, 0.4],
                        &[10.0, 0.5],
                        &[15.0, 0.6],
                        &[20.0, 0.7],
                        &[25.0, 0.8],
                    ],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.15, 0.12, 0.03, -3.0, -6.0, -6.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.15, 0.06, 0.0, -5.0, -10.0, -10.0],
                    &[],
                ),
            ],
            GaugeProperty::Keyboard => vec![
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    100.0,
                    30.0,
                    50.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -1.0, -2.0, -1.0],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    100.0,
                    20.0,
                    70.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -1.0, -3.0, -1.0],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    100.0,
                    20.0,
                    70.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -2.0, -4.0, -2.0],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::LimitIncrement),
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.2, 0.2, 0.1, -4.0, -8.0, -4.0],
                    &[
                        &[10.0, 0.4],
                        &[20.0, 0.5],
                        &[30.0, 0.6],
                        &[40.0, 0.7],
                        &[50.0, 0.8],
                    ],
                ),
                gep(
                    Some(GaugeModifier::LimitIncrement),
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.2, 0.1, 0.0, -6.0, -12.0, -6.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.2, 0.1, 0.0, -100.0, -100.0, -100.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.2, 0.2, 0.1, -1.5, -3.0, -1.5],
                    &[
                        &[5.0, 0.4],
                        &[10.0, 0.5],
                        &[15.0, 0.6],
                        &[20.0, 0.7],
                        &[25.0, 0.8],
                    ],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.2, 0.2, 0.1, -3.0, -6.0, -3.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    0.0,
                    &[0.2, 0.1, 0.0, -5.0, -10.0, -5.0],
                    &[],
                ),
            ],
            GaugeProperty::Lr2 => vec![
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    100.0,
                    20.0,
                    60.0,
                    0.0,
                    &[1.2, 1.2, 0.6, -3.2, -4.8, -1.6],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    100.0,
                    20.0,
                    80.0,
                    0.0,
                    &[1.2, 1.2, 0.6, -3.2, -4.8, -1.6],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::Total),
                    2.0,
                    100.0,
                    20.0,
                    80.0,
                    0.0,
                    &[1.0, 1.0, 0.5, -4.0, -6.0, -2.0],
                    &[],
                ),
                gep(
                    Some(GaugeModifier::ModifyDamage),
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    2.0,
                    &[0.1, 0.1, 0.05, -6.0, -10.0, -2.0],
                    &[&[32.0, 0.6]],
                ),
                gep(
                    Some(GaugeModifier::ModifyDamage),
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    2.0,
                    &[0.1, 0.1, 0.05, -12.0, -20.0, -2.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    2.0,
                    &[0.15, 0.06, 0.0, -100.0, -100.0, -10.0],
                    &[],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    2.0,
                    &[0.10, 0.10, 0.05, -2.0, -3.0, -2.0],
                    &[&[32.0, 0.6]],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    2.0,
                    &[0.10, 0.10, 0.05, -6.0, -10.0, -2.0],
                    &[&[32.0, 0.6]],
                ),
                gep(
                    None,
                    0.0,
                    100.0,
                    100.0,
                    0.0,
                    2.0,
                    &[0.10, 0.10, 0.05, -12.0, -20.0, -2.0],
                    &[],
                ),
            ],
        }
    }
}

/// Gauge element property for each gauge type
#[derive(Clone, Debug)]
pub struct GaugeElementProperty {
    /// Gauge modifier type
    pub modifier: Option<GaugeModifier>,
    /// Gauge change values per judge: PG, GR, GD, BD, PR, MS
    pub value: Vec<f32>,
    /// Minimum gauge value
    pub min: f32,
    /// Maximum gauge value
    pub max: f32,
    /// Initial gauge value
    pub init: f32,
    /// Border value for clearing
    pub border: f32,
    /// Death border
    pub death: f32,
    /// Guts correction table
    pub guts: Vec<Vec<f32>>,
}

#[allow(clippy::too_many_arguments)]
fn gep(
    modifier: Option<GaugeModifier>,
    min: f32,
    max: f32,
    init: f32,
    border: f32,
    death: f32,
    value: &[f32],
    guts: &[&[f32]],
) -> GaugeElementProperty {
    GaugeElementProperty {
        modifier,
        min,
        max,
        init,
        border,
        death,
        value: value.to_vec(),
        guts: guts.iter().map(|g| g.to_vec()).collect(),
    }
}
